import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Toaster } from 'react-hot-toast';
// import { SessionProvider } from 'next-auth/react';
import './globals.css';
import { Provider } from 'react-redux';
import { makeStore } from '@/lib/store';
import StoreProvider from './StoreProvider';
import { ThemeProvider } from 'next-themes';
import 'react-toastify/dist/ReactToastify.css';
import { ToastContainer } from 'react-toastify';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Thrive-Net',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          enableSystem={false}
          // defaultTheme="light"
          attribute="class"
        >
          {/* <SessionProvider> */}
          {/* <Toaster /> */}
          <ToastContainer />
          {children}
          {/* </SessionProvider> */}
        </ThemeProvider>
      </body>
    </html>
  );
}
